name: Update Medium Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-posts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: gh-pages
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install feedparser requests beautifulsoup4
    
    - name: Run update script
      run: |
        source venv/bin/activate
        python update-medium.py
      
    - name: Update Blog Section
      run: |
        source venv/bin/activate
        python update-blog-section.py
        
    - name: Create blog images directory if it doesn't exist
      run: mkdir -p assets/images/blog
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add medium_posts.md index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Medium posts and website [skip ci]" && git push)